# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('first_name', models.TextField(primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('transaction_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contestant')),
            ],
        ),
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contestant')),
            ],
        ),
    ]
