# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('pic', models.ImageField(upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('email', models.TextField()),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contestant')),
            ],
        ),
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to=b'')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contestant')),
            ],
        ),
    ]
