# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='pic',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='goal_amount',
        ),
    ]
