# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 02:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.AddField(
            model_name='donation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 18, 2, 34, 36, 155031, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
